"use client"

import Navbar from '../../../components/layout/Navbar'
import Footer from '../../../components/layout/Footer';
import { Store } from '@/redux/store';
import { Provider } from 'react-redux';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function ClientLayout({
  children,
}: {
  children: React.ReactNode
}) {


  return (
    <html lang="en">

      <body>
        <Provider store={Store}>
          <Navbar />
          <div className="w-[95%] m-auto">
            {children}
          </div>
          <Footer></Footer>
        </Provider>
      </body>
    </html>
  )
}
